### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SevenworksDev** [101arrowz/gd.js#20]
How do you read a message and reply if the subject of the message is a certain word. Sorry, I'm dumb.

**Comment by 101arrowz** [comment]
The docs have some decent info on this. Check out the [LoggedInUser](https://101arrowz.github.io/gd.js/classes/loggedinuser.html) class. Also make sure to follow the [quickstart guide](https://github.com/101arrowz/gd.js#quickstart).

This code is not particularly efficient but it's probably more than good enough for what you're doing. Also it's not tested so use with caution.

```js
import GD from 'gd.js'; // Follow the README instructions if you need to import some other way

// If not in Node.js, set the corsURL to some CORS proxy
// You can set up your own with Heroku from https://github.com/Rob--W/cors-anywhere
const gd = new GD();

// Wait for "time" milliseconds
const wait = time => new Promise(resolve => setTimeout(resolve, time));

// Get all the new messages since "messageId"
async function messagesUpTo(user, messageId) {
  if (messageId == null) return user.getMessages(10);
  for (let i = 10;; i *= 2) {
    // Get the 10 most recent messages
    let fetchedMessages = await user.getMessages(i);
    const index = fetchedMessages.findIndex(msg => msg.id == messageId);
    if (index != -1) return fetchedMessages.slice(0, index);
  }
}

async function autoReply() {
  const me = await gd.users.login({ username: 'you', password: 'yourpassword' });
  // The most recent message ID that was received
  let lastMessageId = null;
  // Constantly check messages
  while (true) {
    const messages = await messagesUpTo(me, lastMessageId);
    lastMessageId = messages[0].id;
    for (const message of messages) {
      if (message.subject == 'YOUR_SUBJECT') {
        // If you need the body of the message:
        // const messageBody = (await message.resolve()).body;
        await user.sendMessage(message.from.accountID, 'your_outgoing_subject', 'your_outgoing_body');
      }
    }
    // Wait 60 seconds before checking again
    await wait(60 * 1000); 
  }
}

autoReply();
```

**Comment by SevenworksDev** [comment]
I'm getting an error and I don't know why.
I'm using node v12.22.6 btw
```
require('isomorphic-fetch');
const GD = require('gd.js');

const gd = new GD({
  logLevel: 0,
  corsURL: 'https://cors-anywhere.herokuapp.com/'
});

const wait = time => new Promise(resolve => setTimeout(resolve, time));

async function messagesUpTo(user, messageId) {
  if (messageId == null) return user.getMessages(10);
  for (let i = 10;; i *= 2) {
    let fetchedMessages = await user.getMessages(i);
    const index = fetchedMessages.findIndex(msg => msg.id == messageId);
    if (index != -1) return fetchedMessages.slice(0, index);
  }
}

async function autoReply() {
  const me = await gd.users.login({ username: process.env.username, password: process.env.password });
  let lastMessageId = null;
  while (true) {
    const messages = await messagesUpTo(me, lastMessageId);
    lastMessageId = messages[0].id;
    for (const message of messages) {
      if (message.subject == 'yourmom') {
        // If you need the body of the message:
        // const messageBody = (await message.resolve()).body;
        await user.sendMessage(message.from.accountID, 'haha', 'you are funny');
      }
    }

    await wait(10 * 1000); 
  }
}

autoReply();
```

Error:
```
(node:540) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Object.exports.gdDecodeBase64 (/home/runner/gdbottest/node_modules/gd.js/lib/util/crypto/node-encdec.js:20:19)
    at new SearchedMessage (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:348:31)
    at /home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:1031:81
    at Array.map (<anonymous>)
    at LoggedInUser.<anonymous> (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:1030:53)
    at step (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:61:23)
    at Object.next (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:42:53)
    at fulfilled (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:33:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 101arrowz** [comment]
CORS-Anywhere doesn't work anymore. Try `https://cors.bridged.cc/`.

Actually you don't even need `corsURL` because you're in Node.js. It's only if you're doing this in a browser. So just use:

```js
const gd = new GD({
  logLevel: 0
});
```

**Comment by SevenworksDev** [comment]
```
(node:110) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at Object.exports.gdDecodeBase64 (/home/runner/gdbottest/node_modules/gd.js/lib/util/crypto/node-encdec.js:20:19)
    at new SearchedMessage (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:348:31)
    at /home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:1031:81
    at Array.map (<anonymous>)
    at LoggedInUser.<anonymous> (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:1030:53)
    at step (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:61:23)
    at Object.next (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:42:53)
    at fulfilled (/home/runner/gdbottest/node_modules/gd.js/lib/entities/user.js:33:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Now I got this error.

**Comment by 101arrowz** [comment]
I'll look into it later but that should work; try increasing your logLevel to 2 to see if the responses are actually correct.

**Comment by SevenworksDev** [comment]
Ok it worked but it showed the html of the cloudflare thing when it did a post request, did post request 6 times and it quit.

**Comment by 101arrowz** [comment]
Either your IP or this program has been blocked by Cloudflare, I'll see if I can reproduce this when I get the chance. In either case it should be a simple fix.

**Comment by SevenworksDev** [comment]
lmao did replit just get blocked

**Comment by SevenworksDev** [comment]
Ok. Now its giving me
```(node:640) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\util\param.js:69:115
    at Array.map (<anonymous>)
    at GDRequestParams.resolve (C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\util\param.js:69:47)
    at Client.<anonymous> (C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\index.js:98:45)
    at step (C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\index.js:54:23)
    at Object.next (C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\index.js:35:53)
    at C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\index.js:29:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\index.js:25:12)
    at Client.req (C:\Users\swd\Desktop\super\Geometry Dash\AutoReply\node_modules\gd.js\lib\index.js:91:16)
(node:640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by 101arrowz** [comment]
I've talked with some people on the GDP Discord and I think the User-Agent needs to be updated, I'll work on this when I get the chance.

**Comment by SevenworksDev** [comment]
Ok.
