### ISSUE TITLE
Resolving yields a TypeError with specfic queries/levels

### ISSUE THREAD

**Issue by cl3847** [101arrowz/gd.js#34]
For example: 
```typescript
const results = await gd.levels.search({query: "100576164"}, 1);
await results[0].resolve());
```
```
TypeError: Cannot read properties of undefined (reading '1')
  at new CustomSong (/project/node_modules/gd.js/lib/entities/level.js:169:21)
  at Level.SearchedLevel (/project/node_modules/gd.js/lib/entities/level.js:283:19)
  at new Level (/project/node_modules/gd.js/lib/entities/level.js:424:24)
  at SearchedLevel.<anonymous> (/project/node_modules/gd.js/lib/entities/level.js:334:51)
  at step (/project/node_modules/gd.js/lib/entities/level.js:61:23)
  at Object.next (/project/node_modules/gd.js/lib/entities/level.js:42:53)
  at fulfilled (/project/node_modules/gd.js/lib/entities/level.js:33:58)
``` 
will yield this error, but other queries like 10565740 will work fine every time. 

This also happens with some level names:
```typescript
await gd.levels.search({query: "backboard"}, 1); // the same level as the ID used in the first example
```
From some digging, it seems like `d` isn't being properly populated sometimes?
```typescript
console.log(d); // { '-': undefined }
```
Any help would be appreciated!

**Comment by Sayajiaji** [comment]
It actually seems to be an issue with using .resolve() with certain levels, somehow I missed that
